<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>ALUMNI UNISZA</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="content-language" content="" />
    <link href="http://fonts.googleapis.com/css?family=Kaushan+Script&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Titillium+Web&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css" />
    <link href="style.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="header"><div id="header2">
            <h1><a href="#">ALUMNI UNISZA</a></h1>
            <div id="menu">
                <ul>
                <li class="active"><a href="index.php">pelajar</a></li>
                    <li class="active"><a href="index2.php">staff</a></li>
                    
                </ul>
            </div>
    </div></div><!-- header --><!-- header2 -->
    <div id="intro"><div id="intro2"><div id="intro3">
      <div id="intro4"><img src="images/unisza_2.png" width="1100" height="200" /></div></div></div></div><!-- intro --><!-- intro2 --><!-- intro3 --><!-- intro4 -->
    <div id="main"><div id="main2">
            <div id="content">
                <div class="post">
                    <h2>&nbsp;</h2>
                    <div class="entry">
                      
                      <table width="510" height="91" border="0" class='easy_share'>
                        <tr>
                          <td width="219" height="48"><font color="black">DAFTAR BARU :</font></td>
                          <td width="281">&nbsp;&nbsp;&nbsp;
                            <button type="button" onclick="document.location.href='register.php';" >TEKAN SINI</button></td>
                        </tr>
                        <tr>
                          <td width="219" height="48"><font color="black">KEMAS KINI :</font></td>
                          <td width="281">&nbsp;&nbsp;&nbsp;
                            <button type="button" onclick="document.location.href='update.php';" >TEKAN SINI</button></td>
                        </tr>
                         <tr>
                          <td width="219" height="48"><font color="black">PAPAR :</font></td>
                          <td width="281">&nbsp;&nbsp;&nbsp;
                            <button type="button" onclick="document.location.href='papar.php';" >TEKAN SINI</button></td>
                        </tr>
                      </table>
                      <p>&nbsp;</p>
                        <p class="readmore">&nbsp;</p>
                    </div>
                </div><!-- post -->
                <div class="post">
                    <h2>&nbsp;</h2>
                    <div class="entry">
                      <p>&nbsp;</p>
                        <p class="readmore">&nbsp;</p>
                    </div>
                </div><!-- post -->	
            </div><!-- content -->
            <div id="sidebar"><!-- box -->
              <h2>&nbsp;</h2>
            </div><!-- sidebar -->
            <div class="clearing">&nbsp;</div>
    </div></div><!-- main --><!-- main2 -->
    <div id="bar"><div id="bar2">
      <div class="clearing">&nbsp;</div>
    </div></div><!-- bar --><!-- bar2 -->
    <div id="footer">
        <div id="footer2">
            <p>Copyright © 2014 Universiti Sultan Zainal Abidin | UniSZA. All Rights Reserved.</a></p>
        </div>
    </div>
</body>
</html>